server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_claim_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.insurance: DEBUG
