server:
  port: 8083

spring:
  application:
    name: policy-service
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_claim_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.insurance: DEBUG
